---
name: Manage `stale` labels
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0,4"

jobs:
  stale-bot:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@6f05e4244c9a0b2ed3401882b05d701dd0a7289b # v7.0.0
        with:
          days-before-stale: 30
          days-before-close: 7
          stale-issue-label: 'state: stale'
          close-issue-label: 'state: rotten'
          stale-pr-label: 'state: stale'
          close-pr-label: 'state: rotten'
          exempt-issue-labels: |
            no-stale
          exempt-pr-labels: |
            no-stale
